name: Slack Notification

on:
  push:
    branches:
    - master
    paths: 
      - 'algos/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      uses: Ilshidur/action-slack@master
      with:
        args: 'A new questions has been pushed to algo-practicar'
